config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  root to: 'videos#index'
  resources :videos

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord

  # Paperclip attachments declaration
  has_attached_file :video_file
  has_attached_file :mp4_file
  has_attached_file :webm_file
  has_attached_file :ogg_file

  has_attached_file :thumbnail, styles: { medium_nr: "250x150!" }

  # Paperclip requires to set attachment validators
  validates_attachment_content_type :video_file, content_type: /\Avideo/
  validates_attachment_content_type :mp4_file, content_type: /.*/
  validates_attachment_content_type :webm_file, content_type: /.*/
  validates_attachment_content_type :ogg_file, content_type: /.*/

  # We want video model always to have :video_file attachment
  validates_attachment_presence :video_file

  # Publish video makes it available
  def publish!
    self.published = true
    save
  end

  # Increment likes counter
  def like!
    self.likes.to_i += 1
    save
  end

  # Decrease likes counter
  def dislike!
    self.likes.to_i -= 1
    save
  end

  # Checks if all formats are already encoded, the simplest way
  def all_formats_encoded?
    self.webm_file.path && self.mp4_file.path ? true : false
  end

  after_create :run_encoders

  private

  def run_encoders
    ThumbnailCutter.perform_async(self.id)
    Mp4VideoEncoder.perform_async(self.id)
    #OgvVideoEncoder.perform_async(self.id)
    WebmVideoEncoder.perform_async(self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :like, :dislike]

  # All published videos
  def index
    @videos = Video.all
  end

  def show
  end

  def new
    @video = Video.new
  end

  def edit
  end

  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # Likes video, increment likes count
  def like
    @video.like!
  end

  # Dislikes video, increment likes count
  def dislike
    @video.dislike!
  end

  private
  def set_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:video_file, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TvControl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    '//vjs.zencdn.net/5.0.2/video-js.css'%>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/videos/_form.html.erb
<%= simple_form_for @video, html: { multipart: true } do |f| %>
  <%= f.input :name %>
  <%= f.input :video_file, as: :file %>
  <%= f.button :submit, class: 'btn-primary', value: 'Upload Video' %>
<% end %>

app/views/videos/edit.html.erb
<h1>Videos#edit</h1>
<%= render 'form' %>

app/views/videos/index.html.erb
<h1>Vídeos</h1>

<div class="row">
  <% @videos.each do |video| %>
    <div class="col-md-3 thumb video-thumb">
      <div class="like">
        <span class="like-count"><%= video.likes %></span>
        <span class="glyphicon glyphicon-heart"></span>
      </div>
      <%= link_to video, class: 'thumbnail' do %>
        <%= image_tag video.thumbnail.url(:medium_nr) %>
      <% end %>
    </div>
  <% end %>
</div>
<div class="row">
  <div class="col-md-12 pull-right">
    <%= link_to 'Upload new video', new_video_url, class: 'btn btn-primary' %>
  </div>
</div>

app/views/videos/new.html.erb
<h1>Videos#new</h1>

<%= render 'form' %>

app/views/videos/show.html.erb
<h1>Videos#show</h1>
<div class="row video-full" data-video-id="<%= @video.id %>">
  <div class⁼"col-md-10">
    <h1> <%= @video.name %> </h1>
      <p class="small">
        <%= link_to 'Back to videos' , videos_path %>

      <% if @video.all_formats_encoded? %>
        <video id="my-video" class="video-js" controls="" data-setup="{}" height="264" preload="auto", width= "640">
          <source src="<%= @video.mp4_file.url %>" type="video/mp4">
          <source src="<%= @video.webm_file.url %>" type="video/webm">
        </video>
      <% end %>
    </p>
  </div>
</div>
          